spring:
  application:
    name: file-service
server:
  error:
    include-message: always
    include-stacktrace: on-param

resilience4j.retry:
  instances:
    storageAzure:
      maxAttempts: 3
      waitDuration: 10s
