spring:
  application:
    name: file-service
  cloud:
    azure:
      storage:
        blob:
          account-name: ${BLOB_STORAGE_ACCOUNT_NAME}
          endpoint: ${BLOB_STORAGE_ENDPOINT}
          account-key: ${BLOB_STORAGE_ACCOUNT_KEY}
          container-name: ${BLOB_STORAGE_CONTAINER_NAME}
server:
  error:
    include-message: always
    include-stacktrace: on-param
