name: CI Build 'main'
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Test JAR
        run: |
          mvn clean verify
      - name: Building JAR
        run: |
          mvn clean install -DskipTests
      - name: Uploading JAR
        uses: actions/upload-artifact@v4
        with:
          name: service-jar
          path: target/app.jar
          retention-days: 2